[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "whichcraft",
    "gevent",
    "gevent-websocket",
    "bottle",
    "bottle_websocket",
    "jinja2"
]
build-backend = "setuptools.build_meta"

