[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "whichcraft",
    "jinja2",
    "flask",
    "flask-sock",
    "werkzeug",
    "atomics",
]
build-backend = "setuptools.build_meta"



